# Generated by Django 2.1.5 on 2020-09-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='uesr',
            new_name='user',
        ),
    ]
